# Dependencies
gems:                [jekyll-paginate]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Jeremy Neal
tagline:             'Software Developer'
description:         "I'm a Baltimore-based software developer. I love programming Clojure and Python mainly, though I always try to learn new skills."
url:                 http://sdroadie.github.io
baseurl:             /
paginate:            5
paginate_path:      '/page-:num/'

# About/contact
author:
  name:              Jeremy Neal
  twitter:           https://twitter.com/@radglob
  github:            https://github.com/sdroadie
  email:             jneal1992@gmail.com

# Custom vars
version:             1.0.0
